// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CaptureFocusedTarget runs in Go so switching away cannot throttle the delay.
 * @returns {$CancellablePromise<$models.FocusTarget>}
 */
export function CaptureFocusedTarget() {
    return $Call.ByID(2444811314).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(17153554).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetDailyHistory returns the study seconds for the last `days` calendar days (7–30),
 * ordered from oldest to newest. Days with no tracked activity have Seconds = 0.
 * @param {number} days
 * @returns {$CancellablePromise<$models.DailyPoint[]>}
 */
export function GetDailyHistory(days) {
    return $Call.ByID(2928107303, days).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Stats>}
 */
export function GetStats() {
    return $Call.ByID(4085168031).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ManualRemind() {
    return $Call.ByID(1271630971);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetCumulative() {
    return $Call.ByID(2143171220);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetToday() {
    return $Call.ByID(1192952464);
}

/**
 * @param {$models.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetConfig(cfg) {
    return $Call.ByID(2748576710, cfg);
}

/**
 * @param {application$0.WebviewWindow | null} win
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(win) {
    return $Call.ByID(739013693, win);
}

/**
 * Save only the interval; unrelated unsaved frontend settings remain untouched.
 * @param {number} minutes
 * @returns {$CancellablePromise<$models.Stats>}
 */
export function SetReminderInterval(minutes) {
    return $Call.ByID(327883147, minutes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function Snooze(minutes) {
    return $Call.ByID(701935330, minutes);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1544680180);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(32783152);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UndoReset() {
    return $Call.ByID(2607934457);
}

// Private type creation functions
const $$createType0 = $models.FocusTarget.createFrom;
const $$createType1 = $models.Config.createFrom;
const $$createType2 = $models.DailyPoint.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.Stats.createFrom;
