// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config contains user settings persisted on disk.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("recognitionVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["recognitionVersion"] = 0;
        }
        if (!("intervalMinutes" in $$source)) {
            /**
             * IntervalMinutes: reminder interval in minutes. v3 allows going smaller than 30.
             * @member
             * @type {number}
             */
            this["intervalMinutes"] = 0;
        }
        if (!("monitorEnabled" in $$source)) {
            /**
             * MonitorEnabled indicates whether the monitor loop counts time.
             * @member
             * @type {boolean}
             */
            this["monitorEnabled"] = false;
        }
        if (!("notifySystem" in $$source)) {
            /**
             * Reminder channels
             * native system toast via Wails notifications service
             * @member
             * @type {boolean}
             */
            this["notifySystem"] = false;
        }
        if (!("notifyPopup" in $$source)) {
            /**
             * in-app modal
             * @member
             * @type {boolean}
             */
            this["notifyPopup"] = false;
        }
        if (!("notifySound" in $$source)) {
            /**
             * webaudio beep
             * @member
             * @type {boolean}
             */
            this["notifySound"] = false;
        }
        if (!("snoozeMinutes" in $$source)) {
            /**
             * SnoozeMinutes: the default snooze duration used by the Snooze button.
             * @member
             * @type {number}
             */
            this["snoozeMinutes"] = 0;
        }
        if (!("autoStart" in $$source)) {
            /**
             * AutoStart: Windows autostart via HKCU\\...\\Run
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("keywords" in $$source)) {
            /**
             * Matching rules
             * if window title contains any keyword -> considered Bilibili
             * @member
             * @type {string[]}
             */
            this["keywords"] = [];
        }
        if (!("processes" in $$source)) {
            /**
             * if process name is in this list -> considered browser; leave empty to allow any
             * @member
             * @type {string[]}
             */
            this["processes"] = [];
        }
        if (!("clockAlwaysOn" in $$source)) {
            /**
             * Clock overlay
             * keep overlay clock visible at full opacity
             * @member
             * @type {boolean}
             */
            this["clockAlwaysOn"] = false;
        }
        if (!("clockFadeAfterSecs" in $$source)) {
            /**
             * fade clock after inactivity seconds
             * @member
             * @type {number}
             */
            this["clockFadeAfterSecs"] = 0;
        }
        if (!("clockAlertMinutes" in $$source)) {
            /**
             * when remaining time <= this value, clock enters alert style
             * @member
             * @type {number}
             */
            this["clockAlertMinutes"] = 0;
        }
        if (!("clockAutoShowAlert" in $$source)) {
            /**
             * if not always-on, auto reveal clock during alert window
             * @member
             * @type {boolean}
             */
            this["clockAutoShowAlert"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField8_0($$parsedSource["keywords"]);
        }
        if ("processes" in $$parsedSource) {
            $$parsedSource["processes"] = $$createField9_0($$parsedSource["processes"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * DailyPoint represents the study seconds for a single calendar day.
 */
export class DailyPoint {
    /**
     * Creates a new DailyPoint instance.
     * @param {Partial<DailyPoint>} [$$source = {}] - The source object to create the DailyPoint.
     */
    constructor($$source = {}) {
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DailyPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyPoint(/** @type {Partial<DailyPoint>} */($$parsedSource));
    }
}

/**
 * FocusTarget describes the foreground window captured after the switch delay.
 */
export class FocusTarget {
    /**
     * Creates a new FocusTarget instance.
     * @param {Partial<FocusTarget>} [$$source = {}] - The source object to create the FocusTarget.
     */
    constructor($$source = {}) {
        if (!("process" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["process"] = "";
        }
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }
        if (!("browser" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["browser"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FocusTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FocusTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FocusTarget(/** @type {Partial<FocusTarget>} */($$parsedSource));
    }
}

/**
 * Stats is pushed to the frontend via events and is also queryable via GetStats().
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("watching" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["watching"] = false;
        }
        if (!("totalWatchedSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalWatchedSeconds"] = 0;
        }
        if (!("cumulativeWatchedSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cumulativeWatchedSeconds"] = 0;
        }
        if (!("sinceLastBreakSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sinceLastBreakSeconds"] = 0;
        }
        if (!("nextBreakInSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nextBreakInSeconds"] = 0;
        }
        if (!("activeTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeTitle"] = "";
        }
        if (!("activeProcess" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeProcess"] = "";
        }
        if (!("day" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["day"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * RFC3339 if snoozed
             * @member
             * @type {string | undefined}
             */
            this["snoozedUntil"] = undefined;
        }
        if (!("dailyAvgSeconds" in $$source)) {
            /**
             * average seconds per active day
             * @member
             * @type {number}
             */
            this["dailyAvgSeconds"] = 0;
        }
        if (!("weeklyAvgSeconds" in $$source)) {
            /**
             * average seconds per day over last 7 days
             * @member
             * @type {number}
             */
            this["weeklyAvgSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
